CREATE DATABASE portafolio;

\c portafolio

CREATE TABLE Users(
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(55) NOT NULL,
    marketing BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    liked BOOLEAN NOT NULL DEFAULT FALSE,
)